import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:yitaku/common/widget/text_style.dart';
import 'package:yitaku/utils/StringRes.dart';
import 'package:yitaku/utils/colorRes.dart';

class TermAndConditionScreen extends StatelessWidget {
  const TermAndConditionScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: ColorRes.buttonColor,
        title: const Text(StringRes.termAndCondition),
        centerTitle: true,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 10),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                SizedBox(height: Get.height * 0.025),
                Center(
                  child: Text(StringRes.termAndConditionForUser,
                      style: overpassRegular(color: const Color(0xFF424242),fontSize: 16,fontWeight: FontWeight.bold)),
                ),
                SizedBox(height: Get.height * 0.04),
                Text("1. TERMS",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_1_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_1_2,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_1_3,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_1_4,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("2. USE LICENSE & RESTRICTIONS",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_2_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_2_2,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_2_3,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_2_4,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("3. YOUR RESPONSIBILITIES",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_3_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_3_2,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_3_3,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_3_4,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_3_5,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_3_6,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("4. LIMITATIONS",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_4_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_4_2,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_4_3,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_4_4,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_4_5,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("5. REVISIONS AND ERRATA",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_5_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("6. AVAILABILITY OF WEBSITE or APP",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_6_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("7. LINKS & THIRD PARTIES",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_7_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("8. WEBSITE or APP TERMS OF USE MODIFICATIONS",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_8_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("9. CONTRIBUTIONS",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_9_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_9_2,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_9_3,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_9_4,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_9_5,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_9_6,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("10. INTELLECTUAL PROPERTY",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_10_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_10_2,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_10_3,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_10_4,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("11. ELECTRONIC COMMUNICATIONS",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_11_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("12. INDEMNITY",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_12_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("13. DISCLAIMER",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_13,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("14. GOVERNING LAW",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_14_2,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_14_1,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
                SizedBox(height: Get.height * 0.05),
                Text("15. CONTACT US",style: overpassRegular(color: ColorRes.color757575,fontSize: 11,fontWeight: FontWeight.bold)),
                SizedBox(height: Get.height * 0.025),
                Text(StringRes.t_and_c_15,style: overpassRegular(color: ColorRes.color757575,fontSize: 11)),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
